### PR TITLE
Bump minimist package 0.0.10->0.2.4 in overrides

### PR DESCRIPTION
**Pull request by mahmoudmoravej**
There is a reported vulnerability in `minimist` package:
image

Unfortunately, all the parent packages still dependent on the `0.0.10` version. So I fixed it in `pnpm>overrides`. We should not expect breaking changes as Minor and Patch numbers are changed but the Major is still 0 which means there is no guarantee.

### CODE REVIEW

**Comment by mahmoudmoravej** [comment]
@patricklafrance The CI gets fail but it is not related to current change. An empty PR raises the same issue. Any resolution?

**Comment by patricklafrance** [comment]
@mahmoudmoravej there's still this message in the error that seems related to the changes:

>  ERR_PNPM_LOCKFILE_CONFIG_MISMATCH  Cannot proceed with the frozen installation. The current "overrides" configuration doesn't match the value found in the lockfile

**Comment by mahmoudmoravej** [comment]
@patricklafrance I fixed it by upgrading the CI pnpm version from 8->9. But, it seems the current state of the main is not passing `pnpm lint:installed-check` as well. 

I am not sure if there is a way to fix it regarding variety of errors it raises:
```
. lint:installed-check: Errors:
. lint:installed-check: @workleap/browserslist-config: eslint: Narrower "engines.node" is needed: ^12.22.0 || ^14.17.0 || >=16.0.0
. lint:installed-check: @workleap/browserslist-config: tsup: Narrower "engines.node" is needed: >=[18](https://github.com/gsoft-inc/wl-web-configs/actions/runs/11348075876/job/31561000903?pr=211#step:10:19).0.0
. lint:installed-check: @workleap/eslint-plugin: @typescript-eslint/eslint-plugin: Narrower "engines.node" is needed: ^18.18.0 || >=20.0.0
. lint:installed-check: @workleap/eslint-plugin: eslint-plugin-import: Narrower "engines.node" is needed: >=4.0.0
. lint:installed-check: @workleap/eslint-plugin: eslint-plugin-jest: Narrower "engines.node" is needed: ^16.10.0 || ^18.12.0 || >=[20](https://github.com/gsoft-inc/wl-web-configs/actions/runs/11348075876/job/31561000903?pr=211#step:10:21).0.0
. lint:installed-check: @workleap/eslint-plugin: eslint-plugin-jsx-a11y: Narrower "engines.node" is needed: >=4.0.0
. lint:installed-check: @workleap/eslint-plugin: eslint-plugin-mdx: Narrower "engines.node" is needed: >=18.0.0
. lint:installed-check: @workleap/eslint-plugin: eslint-plugin-package-json: Narrower "engines.node" is needed: >=18.0.0
. lint:installed-check: @workleap/eslint-plugin: eslint-plugin-react: Narrower "engines.node" is needed: >=4.0.0
. lint:installed-check: @workleap/eslint-plugin: eslint-plugin-react-hooks: Narrower "engines.node" is needed: >=10.0.0
. lint:installed-check: @workleap/eslint-plugin: eslint-plugin-storybook: Narrower "engines.node" is needed: >=18.0.0
. lint:installed-check: @workleap/eslint-plugin: eslint-plugin-testing-library: Narrower "engines.node" is needed: ^12.[22](https://github.com/gsoft-inc/wl-web-configs/actions/runs/11348075876/job/31561000903?pr=211#step:10:23).0 || ^14.17.0 || >=16.0.0
. lint:installed-check: @workleap/eslint-plugin: eslint-plugin-yml: Narrower "engines.node" is needed: ^14.17.0 || >=16.0.0
. lint:installed-check: @workleap/eslint-plugin: jsonc-eslint-parser: Narrower "engines.node" is needed: ^12.22.0 || ^14.17.0 || >=16.0.0
. lint:installed-check: @workleap/eslint-plugin: yaml-eslint-parser: Narrower "engines.node" is needed: ^14.17.0 || >=16.0.0
. lint:installed-check: @workleap/eslint-plugin: @swc/core: Narrower "engines.node" is needed: >=10.0.0
. lint:installed-check: @workleap/eslint-plugin: eslint: Narrower "engines.node" is needed: ^12.22.0 || ^14.17.0 || >=16.0.0
. lint:installed-check: @workleap/eslint-plugin: jest: Narrower "engines.node" is needed: ^14.15.0 || ^16.10.0 || >=18.0.0
. lint:installed-check: @workleap/eslint-plugin: tsup: Narrower "engines.node" is needed: >=18.0.0
. lint:installed-check: @workleap/eslint-plugin: @typescript-eslint/eslint-plugin: Narrower "peerDependencies.@typescript-eslint/parser" is needed: ^7.0.0
. lint:installed-check: @workleap/eslint-plugin: @typescript-eslint/eslint-plugin: Narrower "peerDependencies.eslint" is needed: ^8.56.0
. lint:installed-check: @workleap/eslint-plugin: eslint-plugin-import: Narrower "peerDependencies.eslint" is needed: ^2.0.0 || ^3.0.0 || ^4.0.0 || ^5.0.0 || ^6.0.0 || ^7.2.0 || ^8.0.0
. lint:installed-check: @workleap/eslint-plugin: eslint-plugin-jest: Narrower "peerDependencies.eslint" is needed: ^7.0.0 || ^8.0.0 || ^9.0.0
. lint:installed-check: @workleap/eslint-plugin: eslint-plugin-jsx-a11y: Narrower "peerDependencies.eslint" is needed: ^3.0.0 || ^4.0.0 || ^5.0.0 || ^6.0.0 || ^7.0.0 || ^8.0.0
. lint:installed-check: @workleap/eslint-plugin: eslint-plugin-mdx: Narrower "peerDependencies.eslint" is needed: >=8.0.0
. lint:installed-check: @workleap/eslint-plugin: eslint-plugin-package-json: Narrower "peerDependencies.eslint" is needed: >=8.0.0
. lint:installed-check: @workleap/eslint-plugin: eslint-plugin-react: Narrower "peerDependencies.eslint" is needed: ^3.0.0 || ^4.0.0 || ^5.0.0 || ^6.0.0 || ^7.0.0 || ^8.0.0
. lint:installed-check: @workleap/eslint-plugin: eslint-plugin-react-hooks: Narrower "peerDependencies.eslint" is needed: ^3.0.0 || ^4.0.0 || ^5.0.0 || ^6.0.0 || ^7.0.0 || ^8.0.0-0
. lint:installed-check: @workleap/eslint-plugin: eslint-plugin-storybook: Narrower "peerDependencies.eslint" is needed: >=6.0.0
. lint:installed-check: @workleap/eslint-plugin: eslint-plugin-testing-library: Narrower "peerDependencies.eslint" is needed: ^7.5.0 || ^8.0.0
. lint:installed-check: @workleap/eslint-plugin: eslint-plugin-yml: Narrower "peerDependencies.eslint" is needed: >=6.0.0
. lint:installed-check: @workleap/eslint-plugin: ts-node: Narrower "peerDependencies.typescript" is needed: >=2.7.0
. lint:installed-check: @workleap/eslint-plugin: tsup: Narrower "peerDependencies.typescript" is needed: >=4.5.0
. lint:installed-check: @workleap/postcss-configs: postcss-load-config: Narrower "engines.node" is needed: >=18.0.0
. lint:installed-check: @workleap/postcss-configs: postcss-preset-env: Narrower "engines.node" is needed: ^14.0.0 || ^16.0.0 || >=18.0.0
. lint:installed-check: @workleap/postcss-configs: @swc/core: Narrower "engines.node" is needed: >=10.0.0
. lint:installed-check: @workleap/postcss-configs: eslint: Narrower "engines.node" is needed: ^12.22.0 || ^14.17.0 || >=16.0.0
. lint:installed-check: @workleap/postcss-configs: jest: Narrower "engines.node" is needed: ^14.15.0 || ^16.10.0 || >=18.0.0
. lint:installed-check: @workleap/postcss-configs: tsup: Narrower "engines.node" is needed: >=18.0.0
. lint:installed-check: @workleap/postcss-configs: typescript: Narrower "engines.node" is needed: >=14.17.0
. lint:installed-check: @workleap/postcss-configs: postcss-preset-env: Narrower "peerDependencies.postcss" is needed: ^8.4.6
. lint:installed-check: @workleap/postcss-configs: tsup: Narrower "peerDependencies.postcss" is needed: ^8.4.12
. lint:installed-check: @workleap/stylelint-configs: stylelint-config-standard: Narrower "engines.node" is needed: >=18.12.0
. lint:installed-check: @workleap/stylelint-configs: stylelint-prettier: Narrower "engines.node" is needed: >=18.12.0
. lint:installed-check: @workleap/stylelint-configs: eslint: Narrower "engines.node" is needed: ^12.22.0 || ^14.17.0 || >=16.0.0
. lint:installed-check: @workleap/stylelint-configs: tsup: Narrower "engines.node" is needed: >=18.0.0
. lint:installed-check: @workleap/stylelint-configs: typescript: Narrower "engines.node" is needed: >=14.17.0
. lint:installed-check: @workleap/stylelint-configs: stylelint-prettier: Narrower "peerDependencies.prettier" is needed: >=3.0.0
. lint:installed-check: @workleap/stylelint-configs: stylelint-config-standard: Narrower "peerDependencies.stylelint" is needed: ^16.1.0
. lint:installed-check: @workleap/stylelint-configs: stylelint-prettier: Narrower "peerDependencies.stylelint" is needed: >=16.0.0
. lint:installed-check: @workleap/swc-configs: @swc/core: Narrower "engines.node" is needed: >=10.0.0
. lint:installed-check: @workleap/swc-configs: eslint: Narrower "engines.node" is needed: ^12.22.0 || ^14.17.0 || >=16.0.0
. lint:installed-check: @workleap/swc-configs: jest: Narrower "engines.node" is needed: ^14.15.0 || ^16.10.0 || >=18.0.0
. lint:installed-check: @workleap/swc-configs: tsup: Narrower "engines.node" is needed: >=18.0.0
. lint:installed-check: @workleap/swc-configs: typescript: Narrower "engines.node" is needed: >=14.17.0
. lint:installed-check: @workleap/swc-configs: tsup: Narrower "peerDependencies.@swc/core" is needed: ^1.0.0
. lint:installed-check: @workleap/swc-configs: @swc/core: Narrower "peerDependencies.@swc/helpers" is needed: ^0.5.0
. lint:installed-check: @workleap/tsup-configs: @swc/core: Narrower "engines.node" is needed: >=10.0.0
. lint:installed-check: @workleap/tsup-configs: eslint: Narrower "engines.node" is needed: ^12.22.0 || ^14.17.0 || >=16.0.0
. lint:installed-check: @workleap/tsup-configs: jest: Narrower "engines.node" is needed: ^14.15.0 || ^16.10.0 || >=18.0.0
. lint:installed-check: @workleap/tsup-configs: tsup: Narrower "engines.node" is needed: >=18.0.0
. lint:installed-check: @workleap/tsup-configs: typescript: Narrower "engines.node" is needed: >=14.17.0
. lint:installed-check: @workleap/tsup-configs: tsup: Narrower "peerDependencies.typescript" is needed: >=4.5.0
. lint:installed-check: @workleap/webpack-configs: @pmmmwh/react-refresh-webpack-plugin: Narrower "engines.node" is needed: >=10.13.0
. lint:installed-check: @workleap/webpack-configs: @svgr/webpack: Narrower "engines.node" is needed: >=14.0.0
. lint:installed-check: @workleap/webpack-configs: css-loader: Narrower "engines.node" is needed: >=18.12.0
. lint:installed-check: @workleap/webpack-configs: html-webpack-plugin: Narrower "engines.node" is needed: >=10.13.0
. lint:installed-check: @workleap/webpack-configs: mini-css-extract-plugin: Narrower "engines.node" is needed: >=12.13.0
. lint:installed-check: @workleap/webpack-configs: postcss-loader: Narrower "engines.node" is needed: >=18.12.0
. lint:installed-check: @workleap/webpack-configs: react-refresh: Narrower "engines.node" is needed: >=0.10.0
. lint:installed-check: @workleap/webpack-configs: style-loader: Narrower "engines.node" is needed: >=18.12.0
. lint:installed-check: @workleap/webpack-configs: terser-webpack-plugin: Narrower "engines.node" is needed: >=10.13.0
. lint:installed-check: @workleap/webpack-configs: @svgr/core: Narrower "engines.node" is needed: >=14.0.0
. lint:installed-check: @workleap/webpack-configs: @swc/core: Narrower "engines.node" is needed: >=10.0.0
. lint:installed-check: @workleap/webpack-configs: eslint: Narrower "engines.node" is needed: ^12.22.0 || ^14.17.0 || >=16.0.0
. lint:installed-check: @workleap/webpack-configs: jest: Narrower "engines.node" is needed: ^14.15.0 || ^16.10.0 || >=18.0.0
. lint:installed-check: @workleap/webpack-configs: tsup: Narrower "engines.node" is needed: >=18.0.0
. lint:installed-check: @workleap/webpack-configs: typescript: Narrower "engines.node" is needed: >=14.17.0
. lint:installed-check: @workleap/webpack-configs: swc-loader: Narrower "peerDependencies.@swc/core" is needed: ^1.2.147
. lint:installed-check: @workleap/webpack-configs: tsup: Narrower "peerDependencies.@swc/core" is needed: ^1.0.0
. lint:installed-check: @workleap/webpack-configs: @swc/core: Narrower "peerDependencies.@swc/helpers" is needed: ^0.5.0
. lint:installed-check: @workleap/webpack-configs: postcss-loader: Narrower "peerDependencies.postcss" is needed: ^7.0.0 || ^8.0.1
. lint:installed-check: @workleap/webpack-configs: tsup: Narrower "peerDependencies.postcss" is needed: ^8.4.12
. lint:installed-check: @workleap/webpack-configs: @pmmmwh/react-refresh-webpack-plugin: Narrower "peerDependencies.webpack" is needed: ^5.0.0
. lint:installed-check: @workleap/webpack-configs: css-loader: Narrower "peerDependencies.webpack" is needed: ^5.[27](https://github.com/gsoft-inc/wl-web-configs/actions/runs/11348075876/job/31561000903?pr=211#step:10:28).0
. lint:installed-check: @workleap/webpack-configs: html-webpack-plugin: Narrower "peerDependencies.webpack" is needed: ^5.20.0
. lint:installed-check: @workleap/webpack-configs: mini-css-extract-plugin: Narrower "peerDependencies.webpack" is needed: ^5.0.0
. lint:installed-check: @workleap/webpack-configs: postcss-loader: Narrower "peerDependencies.webpack" is needed: ^5.0.0
. lint:installed-check: @workleap/webpack-configs: style-loader: Narrower "peerDependencies.webpack" is needed: ^5.27.0
. lint:installed-check: @workleap/webpack-configs: terser-webpack-plugin: Narrower "peerDependencies.webpack" is needed: ^5.1.0
. lint:installed-check: @workleap/webpack-configs: @pmmmwh/react-refresh-webpack-plugin: Incompatible "peerDependencies.webpack-dev-server" requirement: 3.x || 4.x
. lint:installed-check: @sample/app: react: Narrower "engines.node" is needed: >=0.10.0
. lint:installed-check: @sample/app: react-router-dom: Narrower "engines.node" is needed: >=14.0.0
. lint:installed-check: @sample/app: @swc/core: Narrower "engines.node" is needed: >=10.0.0
. lint:installed-check: @sample/app: @testing-library/react: Narrower "engines.node" is needed: >=18.0.0
. lint:installed-check: @sample/app: browserslist: Narrower "engines.node" is needed: ^6.0.0 || ^7.0.0 || ^8.0.0 || ^9.0.0 || ^10.0.0 || ^11.0.0 || ^12.0.0 || >=13.7.0
. lint:installed-check: @sample/app: cross-env: Narrower "engines.node" is needed: >=10.14.0
. lint:installed-check: @sample/app: eslint: Narrower "engines.node" is needed: ^12.22.0 || ^14.17.0 || >=16.0.0
. lint:installed-check: @sample/app: http-server: Narrower "engines.node" is needed: >=12.0.0
. lint:installed-check: @sample/app: identity-obj-proxy: Narrower "engines.node" is needed: >=4.0.0
. lint:installed-check: @sample/app: jest: Narrower "engines.node" is needed: ^14.15.0 || ^16.10.0 || >=18.0.0
. lint:installed-check: @sample/app: jest-environment-jsdom: Narrower "engines.node" is needed: ^14.15.0 || ^16.10.0 || >=18.0.0
. lint:installed-check: @sample/app: msw: Narrower "engines.node" is needed: >=18.0.0
. lint:installed-check: @sample/app: nodemon: Narrower "engines.node" is needed: >=10.0.0
. lint:installed-check: @sample/app: postcss: Narrower "engines.node" is needed: ^10.0.0 || ^12.0.0 || >=14.0.0
. lint:installed-check: @sample/app: stylelint: Narrower "engines.node" is needed: >=18.12.0
. lint:installed-check: @sample/app: ts-jest: Narrower "engines.node" is needed: ^16.10.0 || ^18.0.0 || >=20.0.0
. lint:installed-check: @sample/app: typescript: Narrower "engines.node" is needed: >=14.17.0
. lint:installed-check: @sample/app: webpack: Narrower "engines.node" is needed: >=10.13.0
. lint:installed-check: @sample/app: webpack-cli: Narrower "engines.node" is needed: >=14.15.0
. lint:installed-check: @sample/app: webpack-dev-server: Narrower "engines.node" is needed: >=18.12.0
. lint:installed-check: @sample/components: @swc/core: Narrower "engines.node" is needed: >=10.0.0
. lint:installed-check: @sample/components: @testing-library/react: Narrower "engines.node" is needed: >=18.0.0
. lint:installed-check: @sample/components: eslint: Narrower "engines.node" is needed: ^12.22.0 || ^14.17.0 || >=16.0.0
. lint:installed-check: @sample/components: identity-obj-proxy: Narrower "engines.node" is needed: >=4.0.0
. lint:installed-check: @sample/components: jest: Narrower "engines.node" is needed: ^14.15.0 || ^16.10.0 || >=18.0.0
. lint:installed-check: @sample/components: jest-environment-jsdom: Narrower "engines.node" is needed: ^14.15.0 || ^16.10.0 || >=18.0.0
. lint:installed-check: @sample/components: react: Narrower "engines.node" is needed: >=0.10.0
. lint:installed-check: @sample/components: tsup: Narrower "engines.node" is needed: >=18.0.0
. lint:installed-check: @sample/components: typescript: Narrower "engines.node" is needed: >=14.17.0
. lint:installed-check: @sample/components: @testing-library/react: Narrower "peerDependencies.react" is needed: ^18.0.0
. lint:installed-check: @sample/components: react-dom: Narrower "peerDependencies.react" is needed: ^18.2.0
. lint:installed-check: @sample/components: @testing-library/react: Narrower "peerDependencies.react-dom" is needed: ^18.0.0
. lint:installed-check: @sample/utils: eslint: Narrower "engines.node" is needed: ^12.22.0 || ^14.17.0 || >=16.0.0
. lint:installed-check: @sample/utils: tsup: Narrower "engines.node" is needed: >=18.0.0
. lint:installed-check: @sample/utils: typescript: Narrower "engines.node" is needed: >=14.17.0
. lint:installed-check: Suggestions:
. lint:installed-check: @workleap/browserslist-config: Combined "engines.node" needs to be narrower: >=18.0.0
. lint:installed-check: @workleap/eslint-plugin: Combined "engines.node" needs to be narrower: ^18.18.0 || >=20.0.0
. lint:installed-check: @workleap/eslint-plugin: Combined "peerDependencies.@typescript-eslint/parser" needs to be narrower: ^7.0.0
. lint:installed-check: @workleap/eslint-plugin: Combined "peerDependencies.eslint" needs to be narrower: ^8.56.0
. lint:installed-check: @workleap/eslint-plugin: Combined "peerDependencies.typescript" needs to be narrower: >=4.5.0
. lint:installed-check: @workleap/postcss-configs: Combined "engines.node" needs to be narrower: >=18.0.0
. lint:installed-check: @workleap/postcss-configs: Combined "peerDependencies.postcss" needs to be narrower: ^8.4.12
. lint:installed-check: @workleap/stylelint-configs: Combined "engines.node" needs to be narrower: >=18.12.0
. lint:installed-check: @workleap/stylelint-configs: Combined "peerDependencies.prettier" needs to be narrower: >=3.0.0
. lint:installed-check: @workleap/stylelint-configs: Combined "peerDependencies.stylelint" needs to be narrower: ^16.1.0
. lint:installed-check: @workleap/swc-configs: Combined "engines.node" needs to be narrower: >=18.0.0
. lint:installed-check: @workleap/swc-configs: Combined "peerDependencies.@swc/core" needs to be narrower: ^1.0.0
. lint:installed-check: @workleap/swc-configs: Combined "peerDependencies.@swc/helpers" needs to be narrower: ^0.5.0
. lint:installed-check: @workleap/tsup-configs: Combined "engines.node" needs to be narrower: >=18.0.0
. lint:installed-check: @workleap/tsup-configs: Combined "peerDependencies.typescript" needs to be narrower: >=4.5.0
. lint:installed-check: @workleap/webpack-configs: Combined "engines.node" needs to be narrower: >=18.12.0
. lint:installed-check: @workleap/webpack-configs: Combined "peerDependencies.@swc/core" needs to be narrower: ^1.2.1[47](https://github.com/gsoft-inc/wl-web-configs/actions/runs/11348075876/job/31561000903?pr=211#step:10:48)
. lint:installed-check: @workleap/webpack-configs: Combined "peerDependencies.@swc/helpers" needs to be narrower: ^0.5.0
. lint:installed-check: @workleap/webpack-configs: Combined "peerDependencies.postcss" needs to be narrower: ^8.4.12
. lint:installed-check: @workleap/webpack-configs: Combined "peerDependencies.webpack" needs to be narrower: ^5.27.0
. lint:installed-check: @workleap/webpack-configs: Incompatible combined "peerDependencies.webpack-dev-server" requirements.
. lint:installed-check: @sample/app: Combined "engines.node" needs to be narrower: ^18.12.0 || >=20.0.0
. lint:installed-check: @sample/components: Combined "engines.node" needs to be narrower: >=18.0.0
. lint:installed-check: @sample/components: Combined "peerDependencies.react" needs to be narrower: ^18.2.0
. lint:installed-check: @sample/components: Combined "peerDependencies.react-dom" needs to be narrower: ^18.0.0
. lint:installed-check: @sample/utils: Combined "engines.node" needs to be narrower: >=18.0.0
```

**Comment by patricklafrance** [comment]
@mahmoudmoravej the fix might be to add a minimal PNPM version for every package: https://github.com/voxpelli/node-installed-check/issues/97

Otherwise, I would simply removed `installed-check`.

**Review by patricklafrance — APPROVED** [review]

**Pull request merged**
